# Generated by Django 5.1.5 on 2025-08-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='current_location',
            field=models.CharField(blank=True, help_text='Only admin can update this field.', max_length=255, null=True),
        ),
    ]
