# Generated by Django 5.1.5 on 2025-08-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shipment_current_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='current_location',
            field=models.CharField(default='Los Angeles', editable=False, help_text='Only admin can update this field.', max_length=255),
        ),
    ]
