# Generated by Django 5.1.5 on 2025-08-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_shipment_current_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechat',
            name='message',
        ),
        migrations.AddField(
            model_name='privatechat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='chat_voice/'),
        ),
    ]
