# Generated by Django 5.1.5 on 2025-08-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_privatechat_message_privatechat_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechat',
            name='image',
        ),
        migrations.RemoveField(
            model_name='privatechat',
            name='text',
        ),
        migrations.RemoveField(
            model_name='privatechat',
            name='voice',
        ),
        migrations.AddField(
            model_name='privatechat',
            name='message',
            field=models.TextField(default=1223),
            preserve_default=False,
        ),
    ]
