# Generated by Django 5.1.5 on 2025-08-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_privatechat_image_remove_privatechat_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='mobile',
            field=models.IntegerField(default=2347068848255, max_length=13),
            preserve_default=False,
        ),
    ]
