# Generated by Django 5.1.5 on 2025-08-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_shipment_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='goods_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
